# Engineering Statistics
IMSE 4410 Spring 2016. Copyright 2013-2016 by Timothy Middelkoop License CC by SA 3.0

## Hypothesis Testing - Chapter 9

### In class work

```{r}
pnorm(-0.63,lower.tail=TRUE)
pnorm(0.63,lower.tail=FALSE)

## on board example
alpha <- 0.05
qnorm(alpha/2,lower.tail=FALSE)

qnorm(alpha/2,mean=50,sd=2.5/sqrt(10),lower.tail=FALSE)
qnorm(alpha/2,mean=50,sd=2.5/sqrt(10),lower.tail=TRUE)

```


## Hypothesis Testing II

```{r}
ch09 <- read.csv("data/5e/ch09.csv",header=TRUE)
d <- na.omit(ch09$Example9.6) ; n <- length(d) ; n ## [1] 

plot(d)
qqnorm(d,datax=TRUE) ; qqline(d,datax=TRUE)

alpha <- 0.05
mu0 <- 0.82

xb <- mean(d) ; xb
s <- sd(d) ; s

talpha <- qt(alpha,n-1,lower.tail=FALSE) ; talpha
t0 <- (xb-mu0)/(s/sqrt(n)) ; t0

t.test(d,mu=0.82,alternative="greater")
```
### p-value and $\beta$ values

```{r}
## By hand p-value
n<-15
pt(2.719,n-1,lower.tail=FALSE)

## Using R
ch09 <- read.csv("data/5e/ch09.csv",header=TRUE)
x <- na.omit(ch09$Example9.6) ; n <- length(x) ; n ## [1] 

xb <- mean(x) ; xb
s <- sd(x) ; s
alpha <- 0.05
mu0 <- 0.82
t0 <- (xb-mu0)/(s/sqrt(n)) ; t0
pt(t0,n-1,lower.tail=FALSE)

pt((xb-mu0)/(s/sqrt(n)),n-1,lower.tail=FALSE)

power.t.test(n = NULL,delta = 0.02,sd = s,sig.level = alpha, type = "one.sample", alternative="one.sided", power=0.80)

power.t.test(n = n, delta = 0.02, sd = s,sig.level = alpha, type = "one.sample", alternative="one.sided", power=NULL)


```