# Introduction to Engineering Statistics and R 
Engineering Statistics (IMSE 4410) Spring 2016. 
Copyright 2013-2016 by Timothy Middelkoop License CC by SA 3.0

## Homework Chapter 1-6

Chapter 6 (5e):

1. Exercise 6-2, 6-4, 6-5, 6-9 and 6-11 (by hand, by calculated R, by R function), 6-13
2. Exercise 6-23, 6-33, 6-45, 6-49, 6-53.

A future assignment will require you to demonstrate that you can use RStudio, R and Rmd files.

## Homework Chapter 8
Chapter 8 (5e): 

1. Example 8-4: Mercury Contamination.
2. Exercise 8-3, 8-5, 8-9, 8-11, 8-13, 8-15
3. Exercise 8-23, 8-22 from the tables and the functions.
4. Exercise 8-29, 8-33, 8-41
5. Exercise 8-43 from the tables and the functions.
6. Exercise 8-47, 8-49, 8-51 

## Homework Chapter 9
Chapter 9 (5e):

1. Exercises from 9-1: 9-1, 9-5, 9-7, 9-9, 9-15, 9-17, 9-19
2. Exercises from 9-2: 9-29, 9-33, 9-35, 9-43(a-d)
3. Exercises from 9-3: 9-48, 9-51, 9-53, 9-57(a-b), 9-59(a-d)

Graduate/Extra:

4. Exercises from 9-4: 9-71, 9-74, 9-75, 9-79

## Homework Chapter 11
Chpater 11 (5e)

Do by hand, with R using vectors, and with lm if applicable

1. Exercises from Chapter 11-2: 11-3, 11-5, 11-7, 11-9
2. Exercises from Chapter 11-4: 11-25, 11-27 (1,b,d), 11-29

Do by hand, with R using vectors, and with lm if applicable

3. Section 11-7: 11-53, 11-55 (probability plot is the norm-qq/qqplot)

Do it using the high level functions.

4. Section 11-9: 11-79

## Homework Chapter 12
Chapter 12 (5e)

1. Redo the cacluations using R with vectors and functions for Example 12-1, 12-2 in Chapter 12.
2. 12-5 use matrix calc. for a,b,(graduate/extra c,d) use function calc. for a,b,c,d.
3. 12-7 use function calc.  The solution differs slightly.
4. 12-17 use function calc.  Solutions may differ slightly.
5. Any two odd number of your choice.

## Homework Chapter 13
Chapter 13 (5e)

1. Compute the sst, sse, and ssf for 13-3, 13-5, 13-13 (note the missing values) using the vector and function methods
2. Problems 13-3, 13-5, 13-7, do the calculation by hand, using R with vectors, and R with functions.
   13-7-c do a TurkyHSD analysis instead, which is similar to the text analysis.
3. Problem 13-13 using R functions.
4. Problem 13-37 by hand, R with vectors, and functions.

## Homework Chapter 14
Chapter 14 (5e)

1. Construct contrast table 2^4 by hand without copying (there is a pattern).
2. Example 14-4 in the text.  Do the calculations by hand and using vectors and functions in R.
3. Example 14-5 in the text.  Do the calculations by hand and using vectors and functions in R.  Only calculate Effect A, B, AB, CD, and sst.
4. Exercise 14-13 (14-15 6e): Do by hand, then by using R functions.
5. Exercise 14-27 (14-29 6e): Using R functions.

