# Engineering Statistics
Engineering Statistics (IMSE 4410) Spring 2016. 
Copyright 2013-2016 by Timothy Middelkoop License CC by SA 3.0

## Confidence Intervals - Chapter 8

```{r}
## Example 8.1 in the text.
x <- c(64.1,64.7,64.5,64.6,64.5,64.3,64.6,64.8,64.2,64.3)

sum(x)
n <- 10

qnorm(0.025)
qnorm(0.025,lower.tail=TRUE)

qnorm(0.975)
qnorm(0.025,lower.tail=FALSE)

alpha <- (1-0.95) ; alpha
# upper tail
qnorm(1-alpha/2)
qnorm(alpha/2,lower.tail=FALSE)

## Doing it in R the long way.
x <- c(64.1,64.7,64.5,64.6,64.5,64.3,64.6,64.8,64.2,64.3)

xb <- mean(x); xb
alpha <- 1-0.95 ; alpha
n <- length(x) ; n
z <- qnorm(1-alpha/2,lower.tail=TRUE) ; z
sigma <- 1 

l <- xb-z*sigma/sqrt(n) ; l
u <- xb+z*sigma/sqrt(n) ; u

# Margin of error
me <- z*sigma/sqrt(n) ; me

u <- xb + me ; u
l <- xb - me ; l

```

### Example 8.4

```{r}
ch08 <- read.csv("data/5e/ch08.csv",header=TRUE) 
#names(ch08)
d <- na.omit(data.frame(concentration=ch08$Example8.4))
n <- nrow(d) ; n
length(d)

xb <- mean(d$conc) ; xb
plot(d$con)
hist(d$con)
summary(d)
qqnorm(d$c,datax=TRUE) ; qqline(d$c,datax=TRUE)

pnorm(1.0)
pnorm(-1.5)

hist(rnorm(10000))
qqnorm(rnorm(10000),datax=TRUE)

hist(runif(10000,0,10))
qqnorm(runif(10000,0,10),datax=TRUE)

## Back to the problem
qqnorm(d$c,datax=TRUE) ; qqline(d$c,datax=TRUE)

xb <- mean(d$c) ; xb
n <- nrow(d) ; n
s <- sd(d$c) ; s
alpha <- 1-0.95 ; alpha
qnorm(1-alpha/2,lower.tail=TRUE) 
z <- qnorm(alpha/2,lower.tail=FALSE) ; z

# lower and upper CI
xb - z*s/sqrt(n) 
xb + z*s/sqrt(n) 

# ME
me <- z*s/sqrt(n)
l <- xb - me ; l
u <- xb + me ; u

# After class
alpha <- 1-0.99
z <- qnorm(alpha/2,lower.tail=FALSE) ; z
xb - z*s/sqrt(n) 
xb + z*s/sqrt(n) 

```

## Section 8.2/Example 8.5

```{r}
ch08 <- read.csv("data/5e/ch08.csv",header=TRUE) 
names(ch08)
x <- na.omit(ch08$Ex8.33) ; x 
xb <- mean(x) ; xb
s <- sd(x) ; s
n <- length(x)
sqrt(sum((x-mean(x))^2)/(n-1))
alpha <- 1-0.95

me <- qt(alpha/2,n-1,lower.tail=FALSE)*s/sqrt(n)
xb - me 
xb + me 

```
